version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: LikeKBO
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

    # [추가] DB가 진짜 준비되었는지 도커가 체크하게 만듭니다.

healthcheck:
  test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234" ]
  interval: 5s
  timeout: 5s
  retries: 10